/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.xingray;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(FxApplication.class, args);
    }
}
